name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Eigen
      run: wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz && tar -xvzf eigen-3.4.0.tar.gz

    - name: Download Doctest
      run: wget https://raw.githubusercontent.com/doctest/doctest/master/doctest/doctest.h

    - name: Run make
      run: make INCLUDES="-I ./eigen-3.4.0" test

    - name: Run Tests
      run: ./build/test -s
